Team management Feature
marcelo-cm/workman pull request #31
Opened 2024-11-25 01:48 UTC by Leonardomontesqui

Pr time!!!!! just needs the supabase service_role key :)

2024-11-25 10:18 UTC, marcelo-cm commented
<img width="928" alt="image" src="https://github.com/user-attachments/assets/7b3934d7-c1f7-471a-905e-39fba3216d47">

Is this supposed to be here? if so, it looks bad

2024-12-07 15:26 UTC, marcelo-cm requested changes
wazzaaapp

2024-12-08 01:20 UTC, Leonardomontesqui commented on lib/hooks/supabase/useUser.ts
> +        'Yo this is the errror when fetchin session user: ',
Looool this was from when i was trynna figure out why I was getting logged out after creating a user

2024-12-08 01:55 UTC, Leonardomontesqui commented on lib/hooks/supabase/useCompany.ts
> -    columns: (keyof Company)[] | ['*'] = ['*'],
yea, im fetching all

2024-12-08 02:20 UTC, Leonardomontesqui commented on components/(dashboards)/teams/AddUserForm.tsx
> +            ]}
Object.values(Roles).map((role) => ({ id: role }))

2024-12-09 02:15 UTC, Leonardomontesqui commented
New PR

2024-12-10 18:03 UTC, marcelo-cm approved these changes
can go in once these important small changes r done.

2024-12-17 01:15 UTC, merged